// A small subset of 5-letter words for demo purposes
export const WORDS = [
  'ALERT', 'BEACH', 'BRAIN', 'BUILD', 'CAUSE', 'CHAIR', 'CHEST', 'CLAIM', 'CLOCK', 'COACH',
  'COURT', 'COVER', 'CREAM', 'CROSS', 'CROWN', 'CYCLE', 'DANCE', 'DEATH', 'DEPTH', 'DOUBT',
  'DRAFT', 'DREAM', 'DRINK', 'DRIVE', 'EARTH', 'ENTRY', 'ERROR', 'EVENT', 'FAITH', 'FAULT',
  'FIELD', 'FINAL', 'FLOOR', 'FOCUS', 'FORCE', 'FRAME', 'FRONT', 'FRUIT', 'GLASS', 'GRANT',
  'GRASS', 'GREEN', 'GROUP', 'GUIDE', 'HEART', 'HORSE', 'HOTEL', 'HOUSE', 'IMAGE', 'INDEX',
  'INPUT', 'ISSUE', 'JUDGE', 'KNIFE', 'LAUGH', 'LAYER', 'LEVEL', 'LIGHT', 'LIMIT', 'LUNCH',
  'MAJOR', 'MARCH', 'MATCH', 'METAL', 'MODEL', 'MONEY', 'MONTH', 'MOTOR', 'MOUTH', 'MUSIC',
  'NIGHT', 'NOISE', 'NORTH', 'NOVEL', 'NURSE', 'OFFER', 'ORDER', 'OTHER', 'OWNER', 'PANEL',
  'PAPER', 'PARTY', 'PEACE', 'PHASE', 'PHONE', 'PIECE', 'PILOT', 'PITCH', 'PLACE', 'PLANE',
  'PLANT', 'PLATE', 'POINT', 'POUND', 'POWER', 'PRESS', 'PRICE', 'PRIDE', 'PRIZE', 'PROOF',
  'QUEEN', 'RADIO', 'RANGE', 'RATIO', 'REACH', 'REPLY', 'RIGHT', 'RIVER', 'ROUND', 'ROUTE',
  'SCALE', 'SCENE', 'SCOPE', 'SCORE', 'SENSE', 'SHAPE', 'SHARE', 'SHEEP', 'SHEET', 'SHIFT',
  'SHIRT', 'SHOCK', 'SIGHT', 'SKILL', 'SLEEP', 'SMILE', 'SMOKE', 'SOUND', 'SOUTH', 'SPACE',
  'SPEED', 'SPITE', 'SPORT', 'SQUAD', 'STAFF', 'STAGE', 'START', 'STATE', 'STEAM', 'STEEL',
  'STOCK', 'STONE', 'STORE', 'STUDY', 'STUFF', 'STYLE', 'SUGAR', 'TABLE', 'TASTE', 'TEACH',
  'TERRY', 'THEME', 'THING', 'TITLE', 'TOTAL', 'TOUCH', 'TOWER', 'TRACK', 'TRADE', 'TRAIN',
  'TREAT', 'TRUCK', 'TRUST', 'TRUTH', 'UNCLE', 'UNION', 'UNITY', 'VALUE', 'VIDEO', 'VIEWS',
  'VISIT', 'VOICE', 'WASTE', 'WATCH', 'WATER', 'WHILE', 'WHITE', 'WHOLE', 'WOMAN', 'WORLD',
  'WRITE', 'WRONG', 'YOUTH'
];
